# Created by olala7486@gmail.com

application: ntuvb-allstar
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /bower
  static_dir: bower_components

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /tpl
  static_dir: static/tpl

- url: /hello
  script: helloworld.app

- url: /_ah/spi/.*
  script: voting_backend.api

- url: /admin/cronjob
  script: voting.app
  login: admin

- url: /.*
  script: voting.app

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: latest

skip_files:
- ^(.*/)?.*\.pyc$
- ^venv/bin/.*$
- ^venv/include/.*$
- ^db/.*$
