# Created by olala7486@gmail.com

application: ntuvb-allstar
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bower
  static_dir: bower_components

- url: /static
  static_dir: static

- url: /.*
  script: helloworld.app

libraries:
# GAE libraries here
